src/labthings_fastapi/outputs/mjpeg_stream.py

Add methods to grab a single frame, or just the size of the next frame, from an MJPEG stream. These make it easy to add `grab_frame` and `grab_frame_size` to the camera object. It might be nice if they appeared automatically as properties, somehow "on" the MJPEG stream. However, Thing Description doesn't understand nested Things, so it would mess with the simplicity of our current API.
We could of course expose the endpoints without listing them in the TD, but that that point we'd have to add the actions anyway, so why worry.

Grab frame for mjpeg streams

---

src/labthings_fastapi/client/__init__.py
src/labthings_fastapi/descriptors/property.py
tests/test_properties.py
tests/test_websocket.py

I have been writing properties using POST - but both the WoT spec and LabThings 1 use PUT. This is a trivial change, but important to comply with the standard.

Write properties using PUT

---

src/labthings_fastapi/client/in_server.py
src/labthings_fastapi/dependencies/metadata.py
src/labthings_fastapi/dependencies/raw_thing.py
tests/test_dependency_metadata.py

The `ThingStates` dependency was evaluated before actions were run. When taking multiple captures, for example, this meant that the stage position was not updated.
I have resolved this by replacing the dependency with `GetThingStates`, a callable that returns the same dictionary. This updates when it is called, and thus ensures metadata is always fresh. `labthings-picamera2` and `openflexure-microscope-server` have been updated accordingly.

Safer metadata dependency

---

src/labthings_fastapi/thing_server.py

The `thing_settings` object is currently discarded when the server stops, unless it's been explicitly saved. We now attempt to save it.
Future versions may save it only if it's non-empty, which would be neater.

Attempt to save settings on exit for all Things

---

pyproject.toml
src/labthings_fastapi/decorators/__init__.py
src/labthings_fastapi/descriptors/__init__.py
src/labthings_fastapi/descriptors/endpoint.py
src/labthings_fastapi/descriptors/property.py
tests/test_endpoint_decorator.py

I've added a decorator to allow Things to add arbitrary HTTP endpoints. This should be used sparingly as they won't appear in the Thing Description, but it is sometimes very helpful (e.g. for a gallery Thing where we need to download files).

Endpoint decorator

---

src/labthings_fastapi/actions/__init__.py

This means that an invocation's log now contains the stack trace if it fails, rather than simply returning "error".

Log errors in actions to the action's logger

---

src/labthings_fastapi/actions/invocation_model.py
tests/test_action_logging.py

LogRecord objects can have bad message format strings, and this was causing log serialisation to fail - with bad consequences (action objects became un-returnable).
I've now put exception handling in to allow even badly formatted LogRecord objects to be serialised, which should keep the server working and enable bad log statements to be fixed at source (as you know the file/line number).

Don't fail when constructing LogRecordModels from bad logs

---

.github/workflows/publish.yml
.github/workflows/test.yml
pyproject.toml

`labthings-fastapi` can now be installed from PyPI. Each commit will be built and uploaded to test.pypi.org, and tagged versions will be uploaded to the real thing.
Due to an error during testing, `v0.0.1` has already been pushed to PyPI. I will tag the merge commit of this MR; it's not strictly the commit that resulted in the published package, but the code has not changed - this branch only touches CI, and the configuration in `pyproject.toml` is identical to what was published.
I've split the optional dependencies, so there's now a "server" option. This means that the package can be installed without `fastapi`. At present, nothing is guaranteed to work - though the `client` module ought to work OK.

Publish to pypi

---

.github/workflows/test.yml
src/labthings_fastapi/types/numpy.py
tests/test_numpy_type.py

This swaps back to the built in `NDArray` Pydantic type hint, fixing #79 
Fixes #79

Revert pydantic numpy

---

pyproject.toml

I upgraded numpy and required 2.0 to get `pydantic-numpy` working. However, I've since reverted that as it didn't work with the thing descriptions as I hoped. I am now relaxing the numpy specification, as it enable compatibility with some older libraries.

Relax numpy constraint for compatibility with older libraries

---

pyproject.toml

I reverted the move to `pydantic-numpy` but failed to remove the dependency from metadata. This causes problematic interactions with packages that can't use numpy v2 (including the most recent version of OpenCV to work on the Pi).
This removes the dependency on pydantic-numpy to re-enable compatibility with those packages.

Remove no-longer-needed dependency on pydantic-numpy

---

src/labthings_fastapi/actions/__init__.py
src/labthings_fastapi/client/__init__.py
src/labthings_fastapi/client/in_server.py
src/labthings_fastapi/dependencies/action_manager.py
src/labthings_fastapi/dependencies/blocking_portal.py
src/labthings_fastapi/dependencies/metadata.py
src/labthings_fastapi/dependencies/raw_thing.py
src/labthings_fastapi/dependencies/thing_server.py
src/labthings_fastapi/descriptors/action.py
src/labthings_fastapi/file_manager.py
src/labthings_fastapi/outputs/blob.py
src/labthings_fastapi/server/__init__.py
src/labthings_fastapi/utilities/__init__.py
src/labthings_fastapi/utilities/introspection.py
tests/test_blob_output.py

This PR allows blobs to be passed as input to actions. It's not yet fully general, but two important cases are supported:
1. *client* code can pass a `ClientBlobOutput` object as input to an action, for example `blob = thing.acquire_image()` then `thing.process_image(blob)`. This re-uses the blob on the server, so no large data transfer is needed. This does mean it will fail if the second call comes after the first invocation has been deleted.
2. *server* code can pass Blob objects as input to actions, with everything properly type-hinted. As we're using the objects directly, there's no reliance on the action manager and no data transfer overhead.
This should be particularly useful for camera code, for example allowing us to add processing steps that accept an image as input.
I'd like to …

Blob input

---

.coveragerc
.github/workflows/test.yml
pyproject.toml
src/labthings_fastapi/server/fallback.py
tests/test_fallback.py
tests/test_server_cli.py

Adds more information to the fallback server:
* Display the traceback, but this isn't always too helpful
* Optionally pass log history for display
Screenshot with OFM server passing through logs:

Add more information to the fallback server

---

src/labthings_fastapi/server/cli.py

The generation of the argument parser is now a seperate function from calling it. This allows downstream programs to add extra functionality to their argument parser if needed.

Splitting out the generation of the argument parser for the CLI

---

pyproject.toml

This should be possible with setuptools but I followed their docs and it didn't work as I expected.
Closes #97 
Checking in the wheel (and the tarball) the only change is adding the json file:

Switch build system to hatch and add json files to sdist and wheel

---

src/labthings_fastapi/dependencies/invocation.py
src/labthings_fastapi/exceptions.py
tests/test_action_cancel.py

InvocationCancelledError is needed for catching when invocations are cancelled but currently isn't exposed to the new API.
This also changes the exception it inherits from. I assume SystemExit was used so it bypasses `from Exception` because we certainly do not want it interpreted as a full system exit. To keep this behaviour I have sub-classed it from base exception.
This needs to go in with 0.0.10

Add docstring to InvocationCancelledError and expose to new api via exceptions.

---

dev-requirements.txt
pyproject.toml
src/labthings_fastapi/outputs/mjpeg_stream.py
tests/test_mjpeg_stream.py

The `MJPEGStream` output was the single biggest bit of untested code. There is now a very basic test that makes sure it sends a response with at least one frame separator in it.
In doing this, it was necessary to add code to cleanly close the stream. This has changed the signature of the `stop` method, which may require calling code to be updated.
The `TestClient` we use to test without serving on HTTP does not support streaming: this means we get all the frames at once, which limits exactly what can be tested. Adding the code to cleanly stop the stream is important, as otherwise the TestClient would hang.

Test MJPEGStream

---

src/labthings_fastapi/actions/__init__.py
src/labthings_fastapi/descriptors/action.py
tests/test_actions.py

This is a quick fix to #142
It is my understanding that ActionDescriptor.list_invocations would serialise the blob url, but has no BlobIOContextDep dependency. Why it is being called now and not before isn't totally clear to me. But, it seems to fix the error for now.
A more longterm fix where the arguments needed are provided explicitly would be good.

Add BlobIOContextDep to ActionDescriptor.list_invocations so context vars are available

---

.codespellrc
.github/workflows/test.yml
dev-requirements.txt
docs/source/quickstart/quickstart.rst
docs/source/quickstart/quickstart_example.sh
docs/source/wot_core_concepts.rst
pyproject.toml
src/labthings_fastapi/client/in_server.py
src/labthings_fastapi/decorators/__init__.py
src/labthings_fastapi/dependencies/__init__.py
src/labthings_fastapi/dependencies/blocking_portal.py
src/labthings_fastapi/descriptors/action.py
src/labthings_fastapi/descriptors/property.py
src/labthings_fastapi/example_things/__init__.py
src/labthings_fastapi/outputs/blob.py
src/labthings_fastapi/outputs/mjpeg_stream.py
src/labthings_fastapi/server/fallback.py
src/labthings_fastapi/thing.py
src/labthings_fastapi/thing_description/__init__.py
tests/test_example_thing.py
tests/test_fallback.py
tests/test_server_cli.py

Spell checking in CI, these changes are needed to make it pass.
The only code changes are to some test names as it is spell checking `snake_case` and doesn't like `cant` but we cant add an apostrophe to a function name.

Add CodeSpell to Actions, and fix some spellings

---

docs/source/quickstart/counter.py
pyproject.toml
src/labthings_fastapi/actions/__init__.py
src/labthings_fastapi/client/__init__.py
src/labthings_fastapi/client/in_server.py
src/labthings_fastapi/example_things/__init__.py
src/labthings_fastapi/outputs/blob.py
src/labthings_fastapi/server/__init__.py
src/labthings_fastapi/server/cli.py
src/labthings_fastapi/thing_description/__init__.py
src/labthings_fastapi/utilities/object_reference_to_object.py
tests/module_with_deps.py
tests/test_action_cancel.py
tests/test_action_logging.py
tests/test_base_descriptor.py
tests/test_dependencies.py
tests/test_dependencies_2.py
tests/test_example_thing.py
tests/test_property.py
tests/test_server_cli.py

This PR enables the "Bugbear" rule set in `ruff` (`B` codes). I've fixed the resulting linter errors, which are mostly fairly minor things that won't affect the code that runs.
One rule, B903, complains when classes could be implemented with a `dataclasses.dataclass` and in response I've changed a number of classes to be dataclasses. These are in the test code, specifically testing dependencies.
I have amended one of the tests to explicitly test regular classes and dataclasses, with a comment. The regular class is exempted with a `# noqa B903` and an explanation in the docstring. Elsewhere I've just used dataclasses.
Dataclasses won't work if `from __future__ import annotations` is used. This is a known FastAPI issue and I've added an explanation in the module docstring of …

Enable bugbear rules

---

dev-requirements.txt
pyproject.toml
src/labthings_fastapi/client/in_server.py
tests/test_directthingclient.py
tests/test_settings.py

Currently, read-only properties in `DirectThingClient` are "non-data descriptors" (#165).
This PR introduces a unit test to verify read-only properties work as expected (an `AttributeError` is raised on write). It then fixes the behaviour so that the test passes, and fixes `test_settings` (which assumed the old, broken behaviour).
Closes #165

Fix read-only properties in `DirectThingClient`

---

.github/workflows/test.yml
pyproject.toml
src/labthings_fastapi/actions/__init__.py
src/labthings_fastapi/client/__init__.py
src/labthings_fastapi/client/in_server.py
src/labthings_fastapi/decorators/__init__.py
src/labthings_fastapi/dependencies/invocation.py
src/labthings_fastapi/descriptors/action.py
src/labthings_fastapi/descriptors/endpoint.py
src/labthings_fastapi/example_things/__init__.py
src/labthings_fastapi/outputs/blob.py
src/labthings_fastapi/outputs/mjpeg_stream.py
src/labthings_fastapi/properties.py
src/labthings_fastapi/server/__init__.py
src/labthings_fastapi/server/cli.py
src/labthings_fastapi/thing.py
src/labthings_fastapi/thing_description/__init__.py
src/labthings_fastapi/thing_description/_model.py
src/labthings_fastapi/types/numpy.py
src/labthings_fastapi/utilities/introspection.py
tests/test_property.py
typing_tests/thing_definitions.py

I've added some `mypy` flags to enforce everything is annotated, and updated the codebase to get it passing the new, stricter checks.
`mypy` may now be run with `mypy` or `dmypy run`.

Stricter mypy

---

src/labthings_fastapi/exceptions.py
src/labthings_fastapi/thing.py
src/labthings_fastapi/websockets.py
tests/test_websocket.py

This raises a helpful error if observe_property is called with an argument that isn't a DataProperty. Usually, this will be a functional property, which isn't observable.
To-do before merging:
Closes #169

Raise better errors in observe_property, and test them.

---

.github/workflows/test.yml
pyproject.toml
src/labthings_fastapi/actions/__init__.py
src/labthings_fastapi/client/__init__.py
src/labthings_fastapi/client/in_server.py
src/labthings_fastapi/decorators/__init__.py
src/labthings_fastapi/dependencies/invocation.py
src/labthings_fastapi/descriptors/action.py
src/labthings_fastapi/descriptors/endpoint.py
src/labthings_fastapi/example_things/__init__.py
src/labthings_fastapi/outputs/blob.py
src/labthings_fastapi/outputs/mjpeg_stream.py
src/labthings_fastapi/properties.py
src/labthings_fastapi/server/__init__.py
src/labthings_fastapi/server/cli.py
src/labthings_fastapi/thing.py
src/labthings_fastapi/thing_description/__init__.py
src/labthings_fastapi/thing_description/_model.py
src/labthings_fastapi/types/numpy.py
src/labthings_fastapi/utilities/introspection.py
tests/test_actions.py
tests/test_locking_decorator.py
tests/test_property.py
typing_tests/thing_definitions.py

In #101 and #156 it's clear there are situations where we'd like to be able to decorate actions. In #156 @julianstirling shared code that looked like it should work, but failed strangely.
This PR introduces test code for decorated actions. I was expecting it to fail, then I was going to explicitly support `__wrapped__` (which is how `functools.wraps` works) and watch it turn green wearing a smug expression. However, the test passes already: It turns out that reading the docs and using `inspect.signature` rather than accessing magic attributes directly has paid off, because wrapped functions are already supported. Apparently `functools.partial` objects should also work - this might be useful in a couple of places, but isn't relevant to this PR.
Unfortunately this means I can't reproduce …

Test decorated actions

---

src/labthings_fastapi/utilities/introspection.py

Pydantic 2.11 throws and error is `model_config` is used in `create_model`. [The docs](https://docs.pydantic.dev/latest/api/base_model/#pydantic.create_model) say to use `__config__`, this is tested to work with older pydantic too.

Use __config__ not model_config with create_model for pydatic 2.11 compatibility
